name: "Place Order"
description: "Submit a trade order for the next hourly tick (shared exchange)."
title: "ORDER: {TEAM} {SIDE} {QTY} {TICKER}"
labels: ["order"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## AI Sim Exchange — Order Ticket
        Orders are executed at the **next hourly close** (not the last price you see).
        Use **Limit** orders if you want to try predicting price. Market orders execute at the next close.

  - type: input
    id: team
    attributes:
      label: Team name
      description: "Use your exact team identifier (e.g., team1)."
      placeholder: "team1"
    validations:
      required: true

  - type: dropdown
    id: side
    attributes:
      label: Side
      options:
        - BUY
        - SELL
    validations:
      required: true

  - type: dropdown
    id: ticker
    attributes:
      label: Ticker
      description: "Choose one of the 87 tickers in the course universe."
      options:
        - AAPL
        - TSLA
        - AMZN
        - MSFT
        - NVDA
        - GOOGL
        - META
        - NFLX
        - JPM
        - V
        - BAC
        - PYPL
        - DIS
        - T
        - PFE
        - COST
        - INTC
        - KO
        - TGT
        - NKE
        - SPY
        - BA
        - BABA
        - XOM
        - WMT
        - GE
        - CSCO
        - VZ
        - JNJ
        - CVX
        - PLTR
        - SQ
        - SHOP
        - SBUX
        - SOFI
        - HOOD
        - RBLX
        - SNAP
        - AMD
        - UBER
        - FDX
        - ABBV
        - ETSY
        - MRNA
        - LMT
        - GM
        - F
        - LCID
        - CCL
        - DAL
        - UAL
        - AAL
        - TSM
        - SONY
        - ET
        - MRO
        - COIN
        - RIVN
        - RIOT
        - CPRX
        - VWO
        - SPYG
        - NOK
        - ROKU
        - VIAC
        - ATVI
        - BIDU
        - DOCU
        - ZM
        - PINS
        - TLRY
        - WBA
        - MGM
        - NIO
        - C
        - GS
        - WFC
        - ADBE
        - PEP
        - UNH
        - CARR
        - HCA
        - TWTR
        - BILI
        - SIRI
        - FUBO
        - RKT
    validations:
      required: true

  - type: input
    id: qty
    attributes:
      label: Quantity (shares)
      description: "Integer number of shares."
      placeholder: "10"
    validations:
      required: true

  - type: dropdown
    id: order_type
    attributes:
      label: Order type
      options:
        - MARKET
        - LIMIT
    validations:
      required: true

  - type: input
    id: limit_price
    attributes:
      label: Limit price (only if LIMIT)
      description: "If LIMIT: BUY fills if next_low <= limit, SELL fills if next_high >= limit."
      placeholder: "e.g., 187.50"
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Notes (optional)
      description: "Optional justification or strategy note."
      placeholder: "Optional..."
    validations:
      required: false

  - type: checkboxes
    id: rules_ack
    attributes:
      label: Acknowledgement
      options:
        - label: "I understand MARKET executes at the next hourly close."
          required: true
        - label: "I understand LIMIT may not fill if price never touches my limit."
          required: true
